sudo: required
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
branches:
 only:
   - master
services:
  - mongodb
before_script:
  - echo "replication:" | sudo tee -a /etc/mongod.conf 
  - |-
    echo "  replSetName: \"test\"" | sudo tee -a /etc/mongod.conf
  - sudo service mongod restart 
  - sleep 50
  - travis_retry npm install
  - |-
    mongo --eval 'rs.initiate({_id:"test", version: 1, members: [{"_id":1, "host":"localhost:27017"}]})'
  - mongo --eval 'rs.status()'
